// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using restaurant_service.DBContext;

#nullable disable

namespace restaurant_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327201710_updatedFoodsDeleteAndAdd")]
    partial class updatedFoodsDeleteAndAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("restaurant_service.Model.Food", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Restaurantid")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restourant_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Restaurantid");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("restaurant_service.Model.Restaurant", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<bool>("account_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("account_suspended")
                        .HasColumnType("boolean");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("postal_code")
                        .HasColumnType("integer");

                    b.Property<int>("verification_code")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("restaurant_service.Model.Food", b =>
                {
                    b.HasOne("restaurant_service.Model.Restaurant", null)
                        .WithMany("menu")
                        .HasForeignKey("Restaurantid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("restaurant_service.Model.Restaurant", b =>
                {
                    b.Navigation("menu");
                });
#pragma warning restore 612, 618
        }
    }
}
