// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using order_service.DBContext;

#nullable disable

namespace order_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503211602_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("order_service.Model.Order", b =>
                {
                    b.Property<string>("order_id")
                        .HasColumnType("text");

                    b.HasKey("order_id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
