// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using comment_service.DBContext;

#nullable disable

namespace comment_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250708173124_UpdatedModel234")]
    partial class UpdatedModel234
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("comment_service.Model.Comment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("author_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("comment_rating")
                        .HasColumnType("integer");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("delete_requested")
                        .HasColumnType("boolean");

                    b.Property<bool>("deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("reply_to")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restaurant_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("restaurant_rating")
                        .HasColumnType("real");

                    b.PrimitiveCollection<List<string>>("users_that_rated_comment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("id");

                    b.ToTable("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
